# Generated by Django 2.0.7 on 2018-07-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chienviz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='test_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='urls',
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(default='tweet_text'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(default=-1),
        ),
    ]
