# Generated by Django 2.0.7 on 2018-07-18 04:41

import chienviz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chienviz', '0002_auto_20180718_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='tweet',
            name='lines',
            field=chienviz.models.ListField(blank=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='stations',
            field=chienviz.models.ListField(blank=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
