# Generated by Django 2.0.7 on 2018-07-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chienviz', '0003_auto_20180718_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='status',
        ),
    ]
